# Generated by Django 5.0.9 on 2026-05-21 13:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Thesis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('abstract', models.TextField()),
                ('authors', models.JSONField(default=list)),
                ('keywords', models.JSONField(default=list)),
                ('program', models.CharField(choices=[('BS Information System', 'BS Information System'), ('BS Information Technology', 'BS Information Technology'), ('BS Computer Science', 'BS Computer Science'), ('Associate in Computer Technology', 'Associate in Computer Technology')], max_length=64)),
                ('year', models.PositiveSmallIntegerField()),
                ('adviser', models.CharField(blank=True, default='', max_length=160)),
                ('uploaded_file', models.FileField(max_length=512, upload_to='theses/%Y/')),
                ('file_type', models.CharField(choices=[('pdf', 'PDF'), ('docx', 'DOCX')], max_length=8)),
                ('sha256', models.CharField(db_index=True, max_length=64, unique=True)),
                ('extracted_text', models.TextField(blank=True, default='')),
                ('embedding_status', models.CharField(choices=[('not_started', 'Not Started'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], default='not_started', max_length=16)),
                ('status', models.CharField(choices=[('pending_review', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending_review', max_length=16)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_theses', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_theses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'theses',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='theses_status_created_idx'), models.Index(fields=['program'], name='theses_program_idx'), models.Index(fields=['year'], name='theses_year_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='thesis',
            constraint=models.CheckConstraint(check=models.Q(('status__in', ['pending_review', 'approved', 'rejected'])), name='theses_status_check'),
        ),
        migrations.AddConstraint(
            model_name='thesis',
            constraint=models.CheckConstraint(check=models.Q(('file_type__in', ['pdf', 'docx'])), name='theses_filetype_check'),
        ),
        migrations.AddConstraint(
            model_name='thesis',
            constraint=models.CheckConstraint(check=models.Q(('year__gte', 1980), ('year__lte', 2100)), name='theses_year_range_check'),
        ),
    ]
