# Generated by Django 5.0.9 on 2026-05-23 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='thesis',
            name='embedding_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='thesis',
            name='embedding_model',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='thesis',
            name='embedding_vector',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
