# Generated by Django 5.0.9 on 2026-09-14 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theses', '0002_thesis_embedding_generated_at_thesis_embedding_model_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='thesis',
            options={'ordering': ['-created_at'], 'verbose_name': 'Thesis', 'verbose_name_plural': 'Theses'},
        ),
        migrations.AddField(
            model_name='thesis',
            name='title_embedding',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='thesis',
            name='title_embedding_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
