# Generated by Django 5.0.9 on 2026-09-28 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theses', '0005_title_embedding_source_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='thesis',
            name='processing_job_id',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
    ]
