# Generated by Django 5.0.9 on 2026-09-29 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theses', '0006_thesis_processing_job_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='thesis',
            name='technology_tags',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
