# Generated by Django 5.0.9 on 2026-09-30 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theses', '0007_thesis_technology_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thesis',
            name='program',
            field=models.CharField(choices=[('BS Information System', 'BS Information System'), ('BS Information Technology', 'BS Information Technology'), ('BS Computer Science', 'BS Computer Science')], max_length=64),
        ),
    ]
