# Generated by Django 5.0.9 on 2026-10-05 14:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theses', '0009_title_case_subject_names'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ThesisCitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('detected', 'Detected from references'), ('manual', 'Added manually')], default='detected', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cited', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citations_received', to='theses.thesis')),
                ('citing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citations_made', to='theses.thesis')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='thesiscitation',
            constraint=models.UniqueConstraint(fields=('citing', 'cited'), name='thesis_citation_unique_pair'),
        ),
        migrations.AddConstraint(
            model_name='thesiscitation',
            constraint=models.CheckConstraint(check=models.Q(('citing', models.F('cited')), _negated=True), name='thesis_citation_not_self'),
        ),
    ]
