# Generated by Django 5.0.9 on 2026-09-28 15:24

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessingJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('title', 'Title extraction'), ('metadata', 'Metadata extraction'), ('thesis', 'Thesis upload'), ('identity', 'Identity verification')], max_length=16)),
                ('state', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='queued', max_length=16)),
                ('access_request_id', models.UUIDField(blank=True, null=True)),
                ('private_file_path', models.TextField(blank=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('error', models.JSONField(blank=True, default=dict)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('lease_until', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField()),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['state', 'lease_until', 'created_at'], name='processing__state_e61bec_idx')],
            },
        ),
    ]
