# Generated by Django 5.0.9 on 2026-05-20 15:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_requests', '0003_remove_accessrequest_access_requests_status_check_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='accessrequest',
            name='access_requests_status_check',
        ),
        migrations.AddField(
            model_name='accessrequest',
            name='verification_document_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accessrequest',
            name='verification_result_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accessrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied'), ('processing', 'Processing'), ('auto_approved', 'Auto Approved'), ('pending_manual_review', 'Pending Manual Review')], default='pending', max_length=32),
        ),
        migrations.AddConstraint(
            model_name='accessrequest',
            constraint=models.CheckConstraint(check=models.Q(('status__in', ['pending', 'approved', 'denied', 'processing', 'auto_approved', 'pending_manual_review'])), name='access_requests_status_check'),
        ),
    ]
