# Generated by Django 5.0.9 on 2026-07-30 09:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_requests', '0005_email_verification_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied'), ('processing', 'Processing'), ('auto_approved', 'Auto Approved'), ('pending_manual_review', 'Pending Manual Review'), ('pending_email_verification', 'Pending Email Verification')], default='pending', max_length=32),
        ),
        migrations.AlterField(
            model_name='emailverificationtoken',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
