# Generated by Django 5.0.9 on 2026-05-19 11:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RefreshToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('family_id', models.UUIDField(db_index=True)),
                ('remember_me', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_reason', models.CharField(blank=True, choices=[('rotated', 'Rotated'), ('logout', 'Logout'), ('reuse_detected', 'Reuse Detected'), ('password_reset', 'Password Reset'), ('admin_revoke', 'Admin Revoke')], max_length=40, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_agent', models.CharField(blank=True, max_length=255, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('parent', models.ForeignKey(blank=True, db_column='parent_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='auth_service.refreshtoken')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='refresh_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'refresh_tokens',
                'indexes': [models.Index(condition=models.Q(('revoked_at__isnull', True)), fields=['user'], name='refresh_tokens_user_active_idx'), models.Index(fields=['family_id'], name='refresh_tokens_family_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='refreshtoken',
            constraint=models.CheckConstraint(check=models.Q(('revoked_reason__in', ['rotated', 'logout', 'reuse_detected', 'password_reset', 'admin_revoke']), ('revoked_reason__isnull', True), _connector='OR'), name='refresh_tokens_revoked_reason_check'),
        ),
    ]
