# Generated by Django 5.0.9 on 2026-05-19 11:12

import accounts.models
import django.contrib.postgres.fields.citext
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        # Database extensions required by this module:
        #   - citext: case-insensitive text type used by ``users.email``
        #   - pgcrypto: ``gen_random_uuid()`` and other crypto helpers
        # ``IF NOT EXISTS`` makes the statement idempotent so re-running
        # ``migrate`` against a database that already has them is a no-op.
        # Reverse SQL is a deliberate noop: extensions may be shared with
        # other databases or schemas and dropping them on rollback is
        # unsafe. They will simply persist after a ``migrate zero``.
        migrations.RunSQL(
            sql=[
                'CREATE EXTENSION IF NOT EXISTS citext;',
                'CREATE EXTENSION IF NOT EXISTS pgcrypto;',
            ],
            reverse_sql=[
                migrations.RunSQL.noop,
                migrations.RunSQL.noop,
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', django.contrib.postgres.fields.citext.CIEmailField(max_length=254, unique=True)),
                ('password', models.CharField(blank=True, max_length=128, null=True, verbose_name='password')),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=80)),
                ('role', models.CharField(choices=[('student', 'Student'), ('faculty', 'Faculty'), ('administrator', 'Administrator')], default='student', max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('is_email_verified', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'users',
                'indexes': [models.Index(fields=['role'], name='users_role_idx')],
            },
            managers=[
                ('objects', accounts.models.UserManager()),
            ],
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(check=models.Q(('role__in', ['student', 'faculty', 'administrator'])), name='users_role_check'),
        ),
    ]
