# Generated by Django 5.0.9 on 2026-05-20 14:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('access_requests', '0003_remove_accessrequest_access_requests_status_check_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('auto_approved', 'Auto Approved'), ('pending_manual_review', 'Pending Manual Review'), ('rejected', 'Rejected'), ('error', 'Error')], default='processing', max_length=32)),
                ('extracted_fields', models.JSONField(default=dict)),
                ('ocr_raw_text', models.TextField(blank=True)),
                ('ocr_confidence', models.FloatField(blank=True, null=True)),
                ('decision_reason', models.TextField(blank=True)),
                ('flagged_reasons', models.JSONField(default=list)),
                ('rule_failures', models.JSONField(blank=True, default=list, null=True)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('processor_version', models.CharField(default='mvp-1.0', max_length=100)),
                ('access_request', models.OneToOneField(db_column='access_request_id', on_delete=django.db.models.deletion.CASCADE, related_name='verification_result', to='access_requests.accessrequest')),
            ],
            options={
                'db_table': 'verification_result',
            },
        ),
        migrations.CreateModel(
            name='VerificationDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_path', models.TextField(blank=True, null=True)),
                ('mime_type', models.CharField(max_length=100)),
                ('sha256', models.CharField(db_index=True, max_length=64)),
                ('size_bytes', models.IntegerField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('retention_purge_at', models.DateTimeField(blank=True, null=True)),
                ('purged_at', models.DateTimeField(blank=True, null=True)),
                ('access_request', models.OneToOneField(db_column='access_request_id', on_delete=django.db.models.deletion.CASCADE, related_name='verification_document', to='access_requests.accessrequest')),
            ],
            options={
                'db_table': 'verification_document',
                'indexes': [models.Index(fields=['sha256'], name='ver_doc_sha256_idx'), models.Index(fields=['retention_purge_at'], name='ver_doc_retention_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='verificationresult',
            constraint=models.CheckConstraint(check=models.Q(('status__in', ['processing', 'auto_approved', 'pending_manual_review', 'rejected', 'error'])), name='ver_result_status_check'),
        ),
    ]
