# Generated by Django 5.0.9 on 2026-05-19 11:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('access_requests', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='accessrequest',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, db_column='reviewed_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_access_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='accessrequest',
            index=models.Index(fields=['status', '-created_at'], name='access_requests_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='accessrequest',
            constraint=models.CheckConstraint(check=models.Q(('status__in', ['pending', 'approved', 'denied'])), name='access_requests_status_check'),
        ),
        migrations.AddConstraint(
            model_name='accessrequest',
            constraint=models.CheckConstraint(check=models.Q(('requested_role__in', ['student', 'faculty'])), name='access_requests_requested_role_check'),
        ),
        migrations.AddConstraint(
            model_name='accessrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('email',), name='access_requests_email_pending_uidx'),
        ),
    ]
