# Generated by Django 5.0.9 on 2026-05-20 14:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_requests', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='accessrequest',
            name='access_requests_status_check',
        ),
        migrations.AlterField(
            model_name='accessrequest',
            name='justification',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accessrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied'), ('processing', 'Processing')], default='pending', max_length=16),
        ),
        migrations.AddConstraint(
            model_name='accessrequest',
            constraint=models.CheckConstraint(check=models.Q(('status__in', ['pending', 'approved', 'denied', 'processing'])), name='access_requests_status_check'),
        ),
    ]
